config/routes.rb
Rails.application.routes.draw do

  resources :stockroom_items
  resources :stockroom_removals, except: [:edit]
  resources :stockroom_entries, except: [:edit] do
    put :approve
  end

  resources :accounting_actions
  resources :action_plans
  resources :exercises

  get 'orders/meus_pedidos'
  resources :orders do
    get 'solicitacao'
  end

  resources :requests do
    get 'status'
    resources :request_logs
  end

  resources :uasgs

  resources :item_classifications

  get 'items/for_aquisition'
  resources :items, only: :index

  resources :supplier_groups
  resources :suppliers

  post 'carts/add_item_to_cart'
  get 'carts/remove_item_from_cart'
  get 'carts/finalize'
  resource :cart

  resources :bids do
    resources :items
  end

  get 'home/index'

  root 'home#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

end

app/controllers/accounting_actions_controller.rb
class AccountingActionsController < ApplicationController
  before_action :set_accounting_action, only: [:show, :edit, :update, :destroy]

  # GET /accounting_actions
  # GET /accounting_actions.json
  def index
    @q = AccountingAction.ransack(params[:q])
    @accounting_actions = @q.result(distinct: true)
  end

  # GET /accounting_actions/1
  # GET /accounting_actions/1.json
  def show
  end

  # GET /accounting_actions/new
  def new
    @accounting_action = AccountingAction.new
  end

  # GET /accounting_actions/1/edit
  def edit
  end

  # POST /accounting_actions
  # POST /accounting_actions.json
  def create
    @accounting_action = AccountingAction.new(accounting_action_params)

    respond_to do |format|
      if @accounting_action.save
        format.html { redirect_to @accounting_action, notice: 'Ação foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @accounting_action }
      else
        format.html { render :new }
        format.json { render json: @accounting_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting_actions/1
  # PATCH/PUT /accounting_actions/1.json
  def update
    respond_to do |format|
      if @accounting_action.update(accounting_action_params)
        format.html { redirect_to @accounting_action, notice: 'Ação foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @accounting_action }
      else
        format.html { render :edit }
        format.json { render json: @accounting_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting_actions/1
  # DELETE /accounting_actions/1.json
  def destroy
    @accounting_action.destroy
    respond_to do |format|
      format.html { redirect_to accounting_actions_url, notice: 'Ação foi destruída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_action
      @accounting_action = AccountingAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accounting_action_params
      params.require(:accounting_action).permit(:codigo, :descricao, :exercise_id)
    end
end

app/helpers/accounting_actions_helper.rb
module AccountingActionsHelper
end

app/views/accounting_actions/_form.html.erb
<%= simple_form_for(@accounting_action) do |f| %>
  <%= f.error_notification %>

    <%= f.input :codigo, label: 'Código' %>
    <%= f.input :descricao, label: 'Descrição' %>
    <%= f.association :exercise, label: 'Ano de Exercício', label_method: :nome, collection: Exercise.order('nome DESC'), include_blank: false %>

    <%= f.button :submit, class: 'btn btn-primary'%>
<% end %>

app/views/accounting_actions/edit.html.erb
<h1 class="title">Editando Ação</h1>
	
<%= render 'form' %>

<hr />

<%= link_to 'Mostrar', @accounting_action, class: 'btn btn-info' %>
<%= link_to 'Voltar', accounting_actions_path, class: 'btn btn-default' %>

app/views/accounting_actions/index.html.erb
<h1 class="title">Lista de Ações</h1>


<table class="table table-striped">
  <tr>
      <th><%= sort_link(@q, :codigo, 'Código') %></th>
      <th><%= sort_link(@q, :descricao, 'Descrição', default_order: :asc) %></th>
      <th><%= sort_link(@q, 'exercise_nome', 'Ano') %></th>
      <th colspan="3">Ações</th>
  </tr>
  <tr>
    <%= search_form_for @q do |f| %>
    <td>
      <%= f.search_field :codigo_cont, class: 'form-control' %>
    </td>
    <td>
      <%= f.search_field :descricao_cont, class: 'form-control' %>
    </td>
    <td>
      <%= f.search_field :exercise_nome_cont, class: 'form-control' %>
    </td>
    <td>
      <%= f.submit 'Filtrar', class: 'btn btn-primary' %>
      <%= link_to "Limpar", accounting_actions_path, class: 'btn btn-warning' %>
    </td>
  <% end %>
  </tr>

  <%= content_tag_for(:tr, @accounting_actions) do |accounting_action| %>
          <td><%= accounting_action.codigo %></td>
          <td><%= accounting_action.descricao %></td>
          <td><%= accounting_action.exercise.nome %></td>
        <td>
      <%= link_to 'Mostrar', accounting_action, class: 'btn btn-xs btn-info' %>
      <%= link_to 'Editar', edit_accounting_action_path(accounting_action), class: 'btn btn-xs btn-warning' %>
      <%= link_to 'Destruir', accounting_action, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-xs btn-danger' %>
    </td>
  <% end %>
</table>

<hr />

<%= link_to 'Nova Ação', new_accounting_action_path, class: 'btn btn-success' %>

app/views/accounting_actions/new.html.erb
<h1 class="title">Nova Ação</h1>

<%= render 'form' %>

<hr />

<%= link_to 'Voltar', accounting_actions_path, class: 'btn btn-default' %>

app/views/accounting_actions/show.html.erb
<h1 class="title">Exibindo Ação</h1>

<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @accounting_action.codigo %></dd>
  <dt>Descrição:</dt>
  <dd><%= @accounting_action.descricao %></dd>
  <dt>Ano de Exercício:</dt>
  <dd><%= @accounting_action.exercise.nome %></dd>
</dl>

<hr />

<%= link_to 'Editar', edit_accounting_action_path(@accounting_action), class: 'btn btn-warning' %>
<%= link_to 'Voltar', accounting_actions_path, class: 'btn btn-default' %>