config/routes.rb
Rails.application.routes.draw do

  resources :stockroom_items
  resources :stockroom_removals, except: [:edit]
  resources :stockroom_entries, except: [:edit] do
    put :approve
  end

  resources :accounting_actions
  resources :action_plans
  resources :exercises

  get 'orders/meus_pedidos'
  resources :orders do
    get 'solicitacao'
  end

  resources :requests do
    get 'status'
    resources :request_logs
  end

  resources :uasgs

  resources :item_classifications

  get 'items/for_aquisition'
  resources :items, only: :index

  resources :supplier_groups
  resources :suppliers

  post 'carts/add_item_to_cart'
  get 'carts/remove_item_from_cart'
  get 'carts/finalize'
  resource :cart

  resources :bids do
    resources :items
  end

  get 'home/index'

  root 'home#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

end

app/models/stockroom_item.rb
class StockroomItem < ActiveRecord::Base
  has_many :stockroom_movimentations, dependent: :destroy
  has_many :stockroom_removal_items, dependent: :destroy, autosave: true

  default_scope { order(:descricao) }
end

app/controllers/stockroom_items_controller.rb
class StockroomItemsController < ApplicationController
  load_and_authorize_resource

  before_action :set_stockroom_item, only: [:show, :edit, :update, :destroy]

  # GET /stockroom_items
  # GET /stockroom_items.json
  def index
    @stockroom_items = StockroomItem.all
  end

  # GET /stockroom_items/1
  # GET /stockroom_items/1.json
  def show
    @stockroom_movimentations = StockroomMovimentation.where(stockroom_item: @stockroom_item, aprovada: true)
    @stockroom_item.stockroom_removal_items.each do |sri|
      @stockroom_movimentations << sri.stockroom_movimentation
    end
    @stockroom_movimentations = @stockroom_movimentations.sort_by &:created_at
  end

  # GET /stockroom_items/new
  def new
    @stockroom_item = StockroomItem.new
  end

  # GET /stockroom_items/1/edit
  def edit
  end

  # POST /stockroom_items
  # POST /stockroom_items.json
  def create
    @stockroom_item = StockroomItem.new(stockroom_item_params)

    respond_to do |format|
      if @stockroom_item.save
        format.html { redirect_to @stockroom_item, notice: 'Item criado com sucesso.' }
        format.json { render :show, status: :created, location: @stockroom_item }
      else
        format.html { render :new }
        format.json { render json: @stockroom_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stockroom_items/1
  # PATCH/PUT /stockroom_items/1.json
  def update
    respond_to do |format|
      if @stockroom_item.update(stockroom_item_params)
        format.html { redirect_to @stockroom_item, notice: 'Item foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @stockroom_item }
      else
        format.html { render :edit }
        format.json { render json: @stockroom_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stockroom_items/1
  # DELETE /stockroom_items/1.json
  def destroy
    @stockroom_item.destroy
    respond_to do |format|
      format.html { redirect_to stockroom_items_url, notice: 'Item deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stockroom_item
      @stockroom_item = StockroomItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stockroom_item_params
      params.require(:stockroom_item).permit(:descricao)
    end
end

app/helpers/stockroom_items_helper.rb
module StockroomItemsHelper
end

app/views/stockroom_items/_form.html.erb
<%= simple_form_for(@stockroom_item) do |f| %>
  <%= f.error_notification %>

    <%= f.input :descricao, label: "Descrição" %>

    <%= f.button :submit, value: "Salvar", class: 'btn btn-primary', data: { disable_with: "Processando..." } %>
<% end %>

app/views/stockroom_items/edit.html.erb
<h1 class="title">Editando Stockroom_item</h1>
	
<%= render 'form' %>

<hr />

<%= link_to 'Mostrar', @stockroom_item, class: 'btn btn-info' %>
<%= link_to 'Voltar', stockroom_items_path, class: 'btn btn-default' %>

app/views/stockroom_items/index.html.erb
<h1 class="title">Lista de Itens no Almoxarifado</h1>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Descrição</th>
    <th>Qtd</th>
    <th colspan="3">Ações</th>
  </tr>

  <%= content_tag_for(:tr, @stockroom_items) do |stockroom_item| %>
    <td><%= stockroom_item.id %></td>
    <td><%= stockroom_item.descricao %></td>
    <td><%= stockroom_item.quantidade %></td>
    <td>
      <%= link_to 'Mostrar', stockroom_item, class: 'btn btn-xs btn-info' %>
      <%= link_to 'Editar', edit_stockroom_item_path(stockroom_item), class: 'btn btn-xs btn-warning' if can?(:edit, stockroom_item) %>
      <% if !stockroom_item.stockroom_movimentations.any? %>
        <%= link_to 'Destruir', stockroom_item, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-xs btn-danger' if can?(:destroy, stockroom_item)%>
      <% end %>
    </td>
  <% end %>
</table>

<%= content_tag(:div, class: 'fly-wrapper') do %>
  <%= link_to new_stockroom_item_path, title: 'Adicionar novo item' do %>
    <div class="fly-button">
      <i class="fa fa-plus fly-add-icon"></i>
    </div>
  <% end %>
<% end if can?(:create, StockroomItem) %>

app/views/stockroom_items/new.html.erb
<h1 class="title">Novo Item</h1>

<%= render 'form' %>

<hr />

<%= link_to 'Voltar', stockroom_items_path, class: 'btn btn-default' %>

app/views/stockroom_items/show.html.erb
<h1 class="title">Exibindo Item</h1>

<dl class="dl-horizontal">
  <dt>Descrição:</dt>
  <dd><%= @stockroom_item.descricao %></dd>
  <dt>Saldo:</dt>
  <dd><%= @stockroom_item.quantidade %></dd>
</dl>

<hr />


<div class="col-md-12">
  <h3>Detalhamento das Movimentações</h3>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Tipo Movimentação</th>
      <th>Nº Empenho/Solicitante</th>
      <th>Quantidade</th>
      <th>Saldo</th>
      <th>Data</th>
      <th>Detalhes</th>
    </tr>
    <% saldo = 0 %>
    <% @stockroom_movimentations.each do |sm| %>
      <tr>
        <td><%= sm.id %></td>
        <% if sm.entry? %>
          <td>Entrada</th>
          <td><%= sm.numero_empenho %></td>
          <td>+ <%= sm.quantidade %></td>
          <td><%= saldo += sm.quantidade %></td>
          <td><%= l sm.created_at, format: :short %></td>
          <td><%= link_to "Mais detalhes", stockroom_entry_path(sm)%>
        <% else %>
          <td>Saída</th>
          <td><%= sm.user.full_name %></td>
          <td>- <%= sm.stockroom_removal_items.where(stockroom_item: @stockroom_item).first.quantidade %></td>
          <td><%= saldo -= sm.stockroom_removal_items.where(stockroom_item: @stockroom_item).first.quantidade %></td>
          <td><%= l sm.created_at, format: :short %></td>
          <td><%= link_to "Mais detalhes", stockroom_removal_path(sm) %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>
<hr />

<%= link_to 'Voltar', stockroom_items_path, class: 'btn btn-default' %>