config/routes.rb
Rails.application.routes.draw do

  resources :stockroom_items
  resources :stockroom_removals, except: [:edit]
  resources :stockroom_entries, except: [:edit] do
    put :approve
  end

  resources :accounting_actions
  resources :action_plans
  resources :exercises

  get 'orders/meus_pedidos'
  resources :orders do
    get 'solicitacao'
  end

  resources :requests do
    get 'status'
    resources :request_logs
  end

  resources :uasgs

  resources :item_classifications

  get 'items/for_aquisition'
  resources :items, only: :index

  resources :supplier_groups
  resources :suppliers

  post 'carts/add_item_to_cart'
  get 'carts/remove_item_from_cart'
  get 'carts/finalize'
  resource :cart

  resources :bids do
    resources :items
  end

  get 'home/index'

  root 'home#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id                       :integer          not null, primary key
#  qtd_solicitada           :integer
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  numero_do_empenho        :string(255)
#  classificacao_do_empenho :string(255)
#  fonte_do_empenho         :string(255)
#  data_empenho             :date
#  accounting_action_id     :integer
#  order_id                 :integer
#  item_id                  :integer
#  status                   :integer
#

class Request < ActiveRecord::Base
  # Callbacks
  after_update :add_request_log_about_status_change, :if => Proc.new {|a| a.status_changed?}

  # CONSTANTS
  AGUARDANDO_ENVIO              = 1   # Aguardando envio do formuário para análise orçamentária (Solicitante)
  PEDIDO_ACEITO                 = 2   # Pedido aceito (Analista Orçamentário)
  ENVIADO_PARA_COMPRAS          = 3   # Enviado ao setor de compras (Compras)
  ENVIADO_PARA_EMPENHO          = 4   # Enviado para empenho (Compras)
  EMPENHO_EFETUADO              = 5   # Empenho efetuado (Financeiro)
  ENVIADO_PARA_ALMOXARIFADO     = 6   # Encaminhado para o almoxarifado dar continuidade no processo(Almoxarifado)
  EMPENHO_ENVIADO_AO_FORNECEDOR = 7   # Empenho enviado ao fornecedor (Almoxarifado)
  RECEBIDO_PROVISORIAMENTE      = 8   # Item recebido provisoriamente (Almoxarifado)
  AGUARDANDO_RETIRADA           = 9   # Aguardando retirada do item no almoxarifado (Almoxarifado)
  ITEM_ENTREGUE_AO_SOLICITANTE  = 10  # Item entregue ao solicitante (Almoxarifado)
  FINALIZADO                    = 11  # Requisição Finalizada
  PEDIDO_NEGADO                 = 12  # Pedido negado (Analista Orçamentário)

  STATUS = { 1  => "Aguardando envio do formuário para análise orçamentária",
             2  => "Pedido aceito",
             3  => "Enviado ao setor de compras",
             4  => "Enviado para empenho",
             5  => "Empenho efetuado",
             6  => "Encaminhado para o almoxarifado dar continuidade no processo",
             7  => "Empenho enviado ao fornecedor",
             8  => "Item recebido provisoriamente",
             9  => "Aguardando retirada do item no almoxarifado",
             10 => "Item entregue ao solicitante",
             11 => "Requisição finalizada",
             12 => "Pedido negado" }

  # Associations
  belongs_to :order
  belongs_to :item
  belongs_to :accounting_action
  belongs_to :action_plan
  has_many :request_logs, dependent: :destroy




  def status_detalhado
    STATUS[self.status]
  end

  def add_request_log_about_status_change
    self.request_logs.create(description: "O status foi alterado de <strong>#{STATUS[self.status_was]}</strong> para <strong>#{STATUS[self.status]}</strong>")
  end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to :back, notice: 'Solicitação salva com sucesso.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Solicitação destruída com sucesso.' }
      format.json { head :no_content }
    end
  end

  def status
    @request = Request.find(params[:request_id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:qtd_solicitada, :action_plan_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<h1 class="title">Lista de Pedidos</h1>

<table class="table table-striped">
  <tr>
      <th>qtd_solicitada</th>
      <th colspan="3">Ações</th>
  </tr>

  <%= content_tag_for(:tr, @requests) do |request| %>
          <td><%= request.qtd_solicitada %></td>
        <td>
      <%= link_to 'Mostrar', request %>
      <%= link_to 'Editar', edit_request_path(request) %>
      <%= link_to 'Destruir', request, method: :delete, data: { confirm: 'Você tem certeza?' } %>
    </td>
  <% end %>
</table>

<hr />

<%= link_to 'Novo(a) Request', new_request_path, class: 'btn btn-success' %>

app/views/requests/show.html.erb
<h1 class="title">Exibindo Request</h1>

<dl class="dl-horizontal">
  <dt>Qtd solicitada:</dt>
  <dd><%= @request.qtd_solicitada %></dd>
</dl>

<hr />

<%= link_to 'Editar', edit_request_path(@request), class: 'btn btn-warning' %>
<%= link_to 'Voltar', requests_path, class: 'btn btn-default' %>

app/views/requests/status.html.erb
<h1 class="title">Situação do Item <%= @request.item.item %> da Solicitação nº <%= @request.order.id %></h1>

<dl class="dl-horizontal">
  <dt>Item:</dt>
  <dd><%= @request.item.item %></dd>
  <dt>Descrição:</dt>
  <dd><%= link_to @request.item.descricao, bid_item_path(@request.item.bid, @request.item)  %></dd>
  <dt>Justificativa:</dt>
  <dd><%= @request.justificativa %></dd>
  <dt>Pregão</dt>
  <dd><%= @request.item.bid.numero %></dd>
  <dt>Qtd Solicitada:</dt>
  <dd><%= @request.qtd_solicitada %></dd>
  <dt>Valor Unitário</dt>
  <dd><%= humanized_money_with_symbol @request.item.valor_unitario %></dd>
  <dt>Valor Total</dt>
  <dd><%= humanized_money_with_symbol @request.item.valor_unitario * @request.qtd_solicitada %></dd>
  <dt>Status Atual</dt>
  <dd class="highlight"><strong><%= @request.status_detalhado %></strong></dd>
</dl>

<div class="checkout-wrap">
  <ul class="checkout-bar">
    <li class="<%= ([Request::AGUARDANDO_ENVIO].include? @request.status) ? 'active' : '' %> <%= (@request.status > Request::AGUARDANDO_ENVIO) ? 'visited' : '' %>">Pedido Efetuado</li>
    <li class="<%= ([Request::PEDIDO_ACEITO].include? @request.status) ? 'active' : '' %> <%= (@request.status > Request::PEDIDO_ACEITO) ? 'visited' : '' %> <%= (@request.status == Request::PEDIDO_NEGADO) ? 'denied' : '' %>">Análise Orçamentária</li>
    <li class="<%= ([Request::ENVIADO_PARA_COMPRAS].include? @request.status) ? 'active' : '' %> <%= (@request.status > Request::ENVIADO_PARA_COMPRAS) ? 'visited' : '' %> <%= (@request.status == Request::PEDIDO_NEGADO) ? 'denied' : '' %>">Set. Compras</li>
    <li class="<%= ([Request::EMPENHO_EFETUADO, Request::ENVIADO_PARA_EMPENHO].include? @request.status) ? 'active' : '' %> <%= (@request.status > Request::EMPENHO_EFETUADO) ? 'visited' : '' %> <%= (@request.status == Request::PEDIDO_NEGADO) ? 'denied' : '' %>">Set. Financeiro</li>
    <li class="<%= ([Request::ENVIADO_PARA_ALMOXARIFADO, Request::EMPENHO_ENVIADO_AO_FORNECEDOR, Request::RECEBIDO_PROVISORIAMENTE, Request::AGUARDANDO_RETIRADA, Request::ITEM_ENTREGUE_AO_SOLICITANTE].include? @request.status) ? 'active' : '' %> <%= (@request.status > Request::ITEM_ENTREGUE_AO_SOLICITANTE) ? 'visited' : '' %> <%= (@request.status == Request::PEDIDO_NEGADO) ? 'denied' : '' %>">Set. Almoxarifado</li>
    <li class="<%= ([Request::FINALIZADO].include? @request.status) ? 'visited' : '' %> <%= (@request.status == Request::PEDIDO_NEGADO) ? 'denied' : '' %>">Finalizado</li>
  </ul>
</div>


<h3 class="title">Assentamentos</h3>
<table class="table table-striped">
  <tr>
    <th>Quem?</th>
    <th>Data</th>
    <th>Descrição</th>
    <th>Ações</th>
  </tr>
  <% @request.request_logs.each do |rl| %>
    <tr>
      <td><%= (rl.user) ? rl.user.full_name : 'Sistema' %></td>
      <td><%= l rl.created_at, format: :long %></td>
      <td><%= rl.description.html_safe %></td>
      <td>
        <% if current_user == rl.user %>
          <%= link_to 'Destruir', [@request, rl], method: :delete, data: { confirm: 'Você tem certeza?' } %>
        <% else %>
          &nbsp;
        <% end %>
      </td>
    </tr>
  <% end %>
</table>


<% if can? :create, RequestLog %>
  <hr />
  <h4 class="title">Novo Assentamento</h4>
  <%= render partial: 'request_logs/form' %>
<% end %>