config/routes.rb
Rails.application.routes.draw do

  resources :stockroom_items
  resources :stockroom_removals, except: [:edit]
  resources :stockroom_entries, except: [:edit] do
    put :approve
  end

  resources :accounting_actions
  resources :action_plans
  resources :exercises

  get 'orders/meus_pedidos'
  resources :orders do
    get 'solicitacao'
  end

  resources :requests do
    get 'status'
    resources :request_logs
  end

  resources :uasgs

  resources :item_classifications

  get 'items/for_aquisition'
  resources :items, only: :index

  resources :supplier_groups
  resources :suppliers

  post 'carts/add_item_to_cart'
  get 'carts/remove_item_from_cart'
  get 'carts/finalize'
  resource :cart

  resources :bids do
    resources :items
  end

  get 'home/index'

  root 'home#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                     :integer          not null, primary key
#  item                   :integer
#  item_classification_id :integer
#  descricao              :text(65535)
#  supplier_id            :integer
#  validade               :date
#  unidade                :string(255)
#  quantidade             :integer
#  valor_unitario_cents   :integer
#  tipo                   :string(255)
#  observacao             :text(65535)
#  ativo                  :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  bid_id                 :integer
#  qtd_disponivel         :integer
#

class Item < ActiveRecord::Base # ITENS HOMOLOGADOS

  # Associations
  belongs_to :item_classification
  belongs_to :supplier
  belongs_to :bid
  has_many :requests, dependent: :destroy
  has_many :orders, through: :requests, dependent: :destroy

  # Filters
  #


  # Configs
  monetize :valor_unitario_cents, as: 'valor_unitario' #https://github.com/RubyMoney/money-rails

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :load_resources, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  def for_aquisition
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @bid = Bid.find(params[:bid_id])
    @item = @bid.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @bid = Bid.find(params[:bid_id])
    @item = @bid.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @bid, notice: 'Item criado com sucesso.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @bid, notice: 'Item atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to bid_path(@bid), notice: 'Item destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_resources
      @bid = Bid.find(params[:bid_id])
      @item = @bid.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item, :item_classification_id, :descricao, :supplier_id, :validade, :unidade, :quantidade, :valor_unitario, :tipo, :observacao, :ativo, :bid_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for([@bid, @item]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :item, label: 'Item' %>
    <%= f.association :item_classification, label: 'Classificação', label_method: :nome, input_html: {class: 'chosen-select'} %>
    <%= f.input :descricao, label: 'Descrição' %>
    <%= f.association :supplier, label: 'Fornecedor', label_method: :razao_social, input_html: {class: 'chosen-select'} %>
    <%= f.input :validade, as: :date_picker %>
    <%= f.input :unidade %>
    <%= f.input :quantidade %>
    <%= f.input :valor_unitario, label: 'Valor Unitário ex: (2500,00)', placeholder: '1999,99' %>
    <%= f.input :tipo, collection: [['Consumo', 'Consumo'], ['Permanente', 'Permanente'], ['Serviço', 'Serviço']], input_html: {class: 'chosen-select'} %>
    <%= f.input :observacao, label: 'Observação' %>
    <%= f.input :ativo, input_html: {checked: true} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h3 class="title">Editando Item do Pregão <%= @bid.numero %> / <%= @bid.objeto_do_pregao %></h3>

<%= render 'form' %>

<hr />

<%= link_to 'Mostrar', [@bid, @item], class: 'btn btn-info' %>
<%= link_to 'Voltar', @bid, class: 'btn btn-default' %>

app/views/items/for_aquisition.html.erb
<p class="alert alert-danger">EM FASE DE TESTES!</p>

<h1 class="title">Items Disponíveis para Aquisição</h1>

<a href="<%= cart_path %>"><i class="fa fa-shopping-cart"></i> Carrinho dos Pedidos &nbsp;&nbsp; <span class="badge" id="total-pedidos"><%= session['cart'].count %></span></a>

<hr />

<table class="table table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Classificação</th>
      <th>Descrição</th>
      <th>Fornecedor</th>
      <th>Validade</th>
      <th>Unidade</th>
      <th>Qtd Licitada</th>
      <th>Qtd Disp.</th>
      <th>Valor Unitario</th>
      <th>Tipo</th>
      <th>Solicitação</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item %></td>
        <td><%= item.item_classification.nome %></td>
        <td><%= item.descricao %></td>
        <td><%= item.supplier.razao_social %></td>
        <td><%= l item.validade %></td>
        <td><%= item.unidade %></td>
        <td><%= item.quantidade %></td>
        <td><%= item.qtd_disponivel %></td>
        <td><%= item.valor_unitario %></td>
        <td><%= item.tipo %></td>
        <td>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-<%= item.id %>">
            Fazer Pedido
          </button>

          <!-- Modal -->
          <div class="modal fade" id="modal-<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Item: <%= item.item %> - Pregão: <%= item.bid.numero %></h4>
                </div>
                <div class="modal-body">
                  <p><b>Descrição:</b> <%= item.descricao %></p>
                  <hr />

                  <%= form_tag(carts_add_item_to_cart_path, method: "post") do %>
                    <div class="form-group">
                      <%= hidden_field_tag(:item_id, item.id) %>
                      <p class="form-control-static help-block">Quantidade Disponível: <%= item.qtd_disponivel %></p>
                      <%= label_tag(:quuantidade, 'Quantidade:') %>
                      <%= text_field_tag(:quantidade) %>
                      <br />
                      <br />
                      <%= label_tag(:justificativa, 'Justificativa:') %>
                      <p class="form-control-static help-block small">Apresentar a memória de cálculo para definição da quantidade, razão para aquisição, benefícios que serão alcançados aos alunos/setor, frequência e local de utilização: setor/laboratório</p>
                      <br />
                      <%= text_area_tag(:justificativa) %>
                    </div>
                      <%= submit_tag("Adicionar ao Carrinho") %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <a href="#" class="btn btn-default" data-dismiss="modal">Cancelar</a>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/index.html.erb
<h1 class="title">Lista Geral de Itens</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Classificação</th>
      <th>Descrição</th>
      <th>Fornecedor</th>
      <th>Validade</th>
      <th>Unidade</th>
      <th>Qtd</th>
      <th>Valor Unitario</th>
      <th>Tipo</th>
      <th>Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item %></td>
        <td><%= item.item_classification.nome %></td>
        <td><%= item.descricao %></td>
        <td><%= item.supplier.razao_social %></td>
        <td><%= l item.validade %></td>
        <td><%= item.unidade %></td>
        <td><%= item.quantidade %></td>
        <td><%= item.valor_unitario %></td>
        <td><%= item.tipo %></td>
        <td>
        <% if can? :read, item %>
          <%= link_to 'Mostrar', bid_item_path(item.bid, item) %>
        <% end %>
        <% if can? :update, item %>
          <%= link_to 'Editar', edit_bid_item_path(item.bid, item) %>
        <% end %>
        <% if can? :delete, item %>
          <%= link_to 'Deletar', bid_item_path(item.bid, item), method: :delete, data: { confirm: 'Você tem certeza?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h1 class="title">Novo Item - Pregão <%= @bid.numero %> / <%= @bid.objeto_do_pregao %></h1>

<%= render 'form' %>

<hr />

<%= link_to 'Voltar', bid_items_path, class: 'btn btn-default' %>

app/views/items/show.html.erb
<h3 class="title">Visualizando Item do Pregão <%= @bid.numero %> / <%= @bid.objeto_do_pregao %></h3>

<p>
  <strong>Item:</strong>
  <%= @item.item %>
</p>

<p>
  <strong>Classificação:</strong>
  <%= @item.item_classification.nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @item.descricao %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= link_to @item.supplier.razao_social, @item.supplier %>
</p>

<p>
  <strong>Validade:</strong>
  <%= I18n.l @item.validade %>
</p>

<p>
  <strong>Unidade:</strong>
  <%= @item.unidade %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @item.quantidade %>
</p>

<p>
  <strong>Valor Unitário:</strong>
  <%= humanized_money_with_symbol @item.valor_unitario %>
</p>

<p>
  <strong>Valor Total:</strong>
  <%= humanized_money_with_symbol @item.valor_unitario * @item.quantidade %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @item.tipo %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @item.observacao %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.ativo ? 'Ativo' : "Inativo" %>
</p>

<%= link_to 'Editar', edit_bid_item_path(@bid, @item), class: 'btn btn-warning'%>
<%= link_to 'Voltar', bid_path(@bid), class: 'btn btn-default' %>